#!/bin/bash

# Open this script on a terminal with a long scroll buffer, like:
#   uxterm &

# This will take the random numbers generated by urandom device
# and show them as both characters and hexadecimal numbers.
# It will just keep going.

od -cx /dev/urandom
